### ISSUE TITLE
Artifacts not in Maven Central

### ISSUE THREAD

**Issue by skynetcap** [sava-software/sava#1]
I added the dependencies for 1.9.3 (from https://github.com/sava-software/sava/packages/2225240) to my POM and Maven can't find it in the central artifactory. Any plans to support that? I believe if the artifact isn't published to maven central (Sonatype), you'll have to add a repository to your POM (as it currently stands, I believe). Or is this only a Gradle project?

Also this codebase is super impressive and modern. Amazing work. 

`Could not find artifact software.sava:sava-rpc:jar:1.9.3 in central (https://repo.maven.apache.org/maven2)`

Random note: Making it easy to verify the dependency matches the code (via checksum/SHA512) would help a lot, which is my current task. Since it's a "new" library, it's of high importance, given security considerations.

**Comment by jpe7s** [comment]
I publish to the Github package repository, you will need to wire in your Github username and a [classic personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic) as the password.  Here is an [example in Gradle](https://github.com/sava-software/solana-programs/blob/main/build.gradle#L54), I am not savvy with Maven, but I imagine they have something similar for authenticating to a maven repository.

I do not have time right now to figure out the checksum verification, but completely agree.  Happy to accept any PR to publish anything else to help facilitate.

**Comment by oursy** [comment]
Add the following to your pom.xml to include the required dependencies and repositories:
```xml
<dependencies>
    <!-- Sava framework core functionality -->
    <dependency>
        <groupId>software.sava</groupId>
        <artifactId>sava-core</artifactId>
        <version>1.8.19</version>
    </dependency>

    <!-- Sava framework RPC functionality -->
    <dependency>
        <groupId>software.sava</groupId>
        <artifactId>sava-rpc</artifactId>
        <version>1.8.19</version>
    </dependency>
</dependencies>

<repositories>
    <!-- GitHub repository for Sava framework dependencies -->
    <repository>
        <id>gh1</id>
        <name>sava-software</name>
        <url>https://maven.pkg.github.com/sava-software/software.sava</url>
    </repository>

    <!-- GitHub repository for json-iterator library dependencies -->
    <repository>
        <id>gh2</id>
        <name>comodal</name>
        <url>https://maven.pkg.github.com/comodal/json-iterator</url>
    </repository>
</repositories>
```
You will need to wire in your GitHub username and a classic personal access token [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic)  with read access to packages as the password.

Next, configure the authentication details in your conf/settings.xml:

```xml
<servers>
    <!-- Authentication for the GitHub repository hosting Sava software -->
    <server>
        <id>gh1</id>
        <username>username</username>  <!-- Replace with your GitHub username -->
        <password>access_token</password>  <!-- Replace with your GitHub personal access token -->
    </server>

    <!-- Authentication for the GitHub repository hosting json-iterator -->
    <server>
        <id>gh2</id>
        <username>username</username>  <!-- Replace with your GitHub username -->
        <password>access_token</password>  <!-- Replace with your GitHub personal access token -->
    </server>
</servers>
```
Instructions:
- GitHub Username: Replace username with your actual GitHub username.
- Personal Access Token (PAT): Replace access_token with a GitHub personal access token that has read access to your packages. You can generate this token from your GitHub account under Settings > Developer Settings > Personal Access Tokens.

This configuration allows Maven to authenticate and retrieve the required dependencies from private GitHub repositories.

**Comment by jpe7s** [comment]
What in the AI is going on here!?
