### ISSUE TITLE
Java LTS support

### ISSUE THREAD

**Issue by imaykay** [sava-software/sava#2]
Hi team, I know you explicitly said only latest JDK is supported. And I understand that. At the same time I personally think it would be nice to at least support the latest LTS as well (currently 21). Or maybe even only the LTS if you want to work against one single specific version?

Cheers and thanks for all the hard work you put into your framework!

**Comment by jpe7s** [comment]
Completely understand, but I am the only personal developing this, and it wouldn't be possible without funding.  Also, I am always looking forward to the next set of features being released in each new JDK, which makes it more fun for me.
