### ISSUE TITLE
Use case: Meteora tx deserialization

### ISSUE THREAD

**Issue by imaykay** [sava-software/sava#6]
Hi again,

so here is some background info of how I would like to use the complete framework in the future. I am running a SpringBoot server as execution environment. Inside of that, I would love to basically automate a few things around Meteora DLMM-ing. Three major topics:
1. Analyze own performance
2. Analyze (past) market maker activity
3. Automate position management

For the analyze tasks I would like to gather almost all relevant transactions and store them in my own model in a Mongo so that I am chain independent for finalized transaction when I am adding new metrics. I started with trying to understand Meteora transactions which is why I use deserialization a lot. Not much happened until now, this is the main code snippet which is not running smoothly yet. Latest exception was `software.sava.rpc.json.http.response.JsonRpcException: Invalid param: WrongSize`. But they are obviously always depending on the transactions of the current batch.
```
@SpringBootApplication
public class BaseApplication {
    private static final Logger log = LoggerFactory.getLogger(BaseApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(BaseApplication.class, args);

        try (final var httpClient = HttpClient.newHttpClient()) {
            var rpcClient = SolanaRpcClient.createClient(SolanaNetwork.MAIN_NET.getEndpoint(), httpClient);
            String meteoraProgramId = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo";

            CompletableFuture<List<TxSig>> meteoraSignaturesFuture = rpcClient.getSignaturesForAddress(Commitment.FINALIZED, PublicKey.fromBase58Encoded(meteoraProgramId), 100);
            List<TxSig> meteoraSignatures = meteoraSignaturesFuture.join();
            log.info("Found {} signatures.", meteoraSignatures.size());

            meteoraSignatures.forEach(txSig -> {
                log.info("Going to check signature {}.", txSig.signature());

                CompletableFuture<Tx> transactionFuture = rpcClient.getTransaction(Commitment.FINALIZED, txSig.signature(), 0, RpcEncoding.base64.name());
                Tx transaction = transactionFuture.join();
                byte[] transactionData = transaction.data();

                TransactionSkeleton transactionSkeleton = TransactionSkeleton.deserializeSkeleton(transactionData);
                Instruction[] instructions;
                if (transactionSkeleton.isLegacy()) {
                    instructions = transactionSkeleton.parseInstructions(transactionSkeleton.parseAccounts());
                } else {
                    // Fetch Lookup tables to allow parsing of versioned transactions.
                    int txVersion = transactionSkeleton.version();
                    if (txVersion == 0) {
                        var tableAccountInfos = rpcClient.getMultipleAccounts(
                                Arrays.asList(transactionSkeleton.lookupTableAccounts()),
                                AddressLookupTable.FACTORY).join();

                        var lookupTables = tableAccountInfos.stream()
                                .map(AccountInfo::data)
                                .collect(Collectors.toUnmodifiableMap(AddressLookupTable::address, Function.identity()));

                        instructions = transactionSkeleton.parseInstructions(transactionSkeleton.parseAccounts(lookupTables));
                    } else {
                        throw new IllegalStateException("Unhandled tx version " + txVersion);
                    }
                }

                Arrays.stream(instructions)
                        .filter(LbClmmProgram.ADD_LIQUIDITY_BY_STRATEGY_DISCRIMINATOR)
                        .map(LbClmmProgram.AddLiquidityByStrategyIxData::read)
                        .forEach(ixData -> {
                            LiquidityParameterByStrategy liquidityParameters = ixData.liquidityParameter();
                            log.info("Found add-liquidity-by-strategy with the following params on {}:\nAmountX: {}\nAmountY: {}\nActiveId: {}\nMaxActiveBinSlippage: {}\nMinBinId: {}\nMaxBinId: {}\nStrategyType: {}\nTransaction: {}",
                                    transaction.blockTime(), //
                                    liquidityParameters.amountX(), //
                                    liquidityParameters.amountY(), //
                                    liquidityParameters.activeId(), //
                                    liquidityParameters.maxActiveBinSlippage(), //
                                    liquidityParameters.strategyParameters().minBinId(), //
                                    liquidityParameters.strategyParameters().maxBinId(), //
                                    liquidityParameters.strategyParameters().strategyType(), //
                                    transaction.toString());
                        });
            });
        }
    }
}
```

Any chance that you could get this to run on a few different points in time or with higher signature number? This might be much faster than me stumbling over deserialization exceptions and trying to extract good bug reports from them 😅 I know it's a lot to ask though, so feel free to just say no.

P.S.: I took most of the code from your Drift example.

**Comment by jpe7s** [comment]
Having these cases is great, it helps me focus in on fixing and improving things that are actually useful to people.

I will sit down with this early next week after the [Colosseum Radar hackathon](https://www.colosseum.org/radar) deadline.

**Comment by jpe7s** [comment]
[This was a sneaky one](https://github.com/sava-software/sava/commit/b55845782cfb3d99fef33820b8367c208923bc98#r147719225), the length of some of the instructions was greater than 127 which requires multiple bytes to represent the value.  This hasn't been an issue for me on serialization because my [CompactU16Encoding#encodeLength](https://github.com/sava-software/sava/blob/7d682ccd86711c31867ad8a193851020cbbbe0ed/core/src/main/java/software/sava/core/tx/InstructionRecord.java#L124) utility returns how many bytes were required to represent the value.  I fixed that pattern of behavior across the board for the Skeleton and added a [basic test ](https://github.com/sava-software/sava/blob/7d682ccd86711c31867ad8a193851020cbbbe0ed/core/src/test/java/software/sava/core/tx/TransactionSerializationTests.java#L20).

[dded an example](https://github.com/sava-software/anchor-programs/blob/21f5cfb4943dfea3d38fe14e00f53846cc0f1f9a/examples/src/main/java/software/sava/anchor/program/examples/PageMeteoraTransactions.java#L16) based on your code above to anchor-programs.

Solana's public infrastructure endpoint has very conservative rate limits.  I would recommend getting a Helius RPC API key, even their free tier will be much better.  Also, improved the `getTransaction` methods a bit and with better defaults.

Noticed that you didn't need the accounts from instructions, i've since added a method to allow [parsing v0 instructions without lookup tables](https://github.com/sava-software/anchor-programs/blob/febcf389ad41003334b2d9d6d2145d2a1652a537/examples/src/main/java/software/sava/anchor/program/examples/PageMeteoraTransactions.java#L54).

What method call did you make for the RPC client to complain with `WrongSize`?  The only time I have seen that is when I accidentally passed an empty list to `getMultipleAccounts`.

**Comment by imaykay** [comment]
Hi mate,

thank you sooo much! I will give it a try probably early next week.

I really just executed the code I posted. Maybe there was a special transaction in the ones that were currently finalized and therefore returned at that point in time?

**Comment by jpe7s** [comment]
It was most like a versioned transaction that had zero tables.  Added a [check in the Drift example](https://github.com/sava-software/anchor-programs/blob/251593d1dd41974c721069c0d145764bcc0f6a64/examples/src/main/java/software/sava/anchor/program/examples/ParseDriftPlaceOrdersTransaction.java#L51), and it is no longer applicable to the Meteora example.

**Comment by imaykay** [comment]
Follow up question (which I could possibly figure out myself but it seems waaay faster to just ask as you are so helpful): I guess if I want to also get data from the input accounts, I would need the accounts lookup table, that we just removed?

Will it then be possible to access the accounts by name like they are displayed e.g. on solscan?

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/266f8d86-63b7-43ae-9350-0b14e8504d6f">

**Comment by jpe7s** [comment]
To get all of the account addresses for each instruction, yes you would need all of the lookup tables used.  Example code for that is still in the Drift example. Block explorers or someone else might provide API's for fetching off-chain meta-data associated with accounts, but I have never looked into it.

**Comment by jpe7s** [comment]
Oh you mean the IDL variable names? sorry just looked at the highlighting. You can find those either in the IDL for the account types, or in the code that my generator uses.  But they are not indexed for lookup like the explorer is doing here.

From their IDL, I believe you can download this locally using the anchor CLI, or there is some code in my source gen if you want to build something against it:
```json
      "name": "addLiquidityByStrategy",
      "accounts": [
        {
          "name": "position",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "lbPair",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "binArrayBitmapExtension",
          "isMut": true,
          "isSigner": false,
          "isOptional": true
        },
        {
          "name": "userTokenX",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "userTokenY",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "reserveX",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "reserveY",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "tokenXMint",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "tokenYMint",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "binArrayLower",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "binArrayUpper",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "sender",
          "isMut": false,
          "isSigner": true
        },
        {
          "name": "tokenXProgram",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "tokenYProgram",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "eventAuthority",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "program",
          "isMut": false,
          "isSigner": false
        }
      ]
```

The corresponding code I generate: https://github.com/sava-software/anchor-programs/blob/35dcdada26d3fa01cd7ecf269d26c4c7032852bf/programs/src/main/java/software/sava/anchor/programs/meteora/dlmm/anchor/LbClmmProgram.java#L420

**Comment by jpe7s** [comment]
Not sure where the disconnect is happening.  `position` and `sender` will always be the 1st and 12th account passed to the `addLiquidityByStrategy` instruction.  The accounts ordering will be the same when you parse that instruction.

**Comment by imaykay** [comment]
Duh, was just expecting sth complicated I guess, so wasn't able to see this straightforward way. Thanks again!
