### ISSUE TITLE
SolanaRpcWebsocket

### ISSUE THREAD

**Issue by wangy0531** [sava-software/sava#7]
When using SolanaRpcWebsocket, it seems that I haven't found a way to handle reconnections after a disconnection.

**Comment by wangy0531** [comment]
Yes, you’re right. I encountered this issue when simulating a network disconnection."

**Comment by wangy0531** [comment]
Thank you for your reply.

**Comment by jpe7s** [comment]
I've added the [onError](https://github.com/sava-software/sava/blob/main/rpc/src/main/java/software/sava/rpc/json/http/ws/SolanaRpcWebsocket.java#L163) and [onClose](https://github.com/sava-software/sava/blob/main/rpc/src/main/java/software/sava/rpc/json/http/ws/SolanaRpcWebsocket.java#L161) hooks.  However, by trying to test it out by disconnecting my internet connection, I never received an event, but after re-connecting my network connection, after a few seconds I began to receive messages again.

**Comment by jpe7s** [comment]
appreciate you trying out the library, unless you would like to see a specific change to the web-socket going to close this out tomorrow.
