### ISSUE TITLE
`Tx` type always returns null for `accountKeys()`

### ISSUE THREAD

**Issue by Alec1017** [sava-software/sava#8]
Hey there, 

Im fairly new to sava and i havent explored the code base fully, but i noticed that calls to `accountKeys()` on the `Tx` type keeps returning null.

I did some digging and found this code: 

```java
// rpc/src/main/java/software/sava/rpc/json/http/response/Tx.java

  private static final ContextFieldBufferPredicate<Builder> PARSER = (builder, buf, offset, len, ji) -> {
    if (fieldEquals("slot", buf, offset, len)) {
      builder.slot(ji.readInt());
    } else if (fieldEquals("blockTime", buf, offset, len)) {
      builder.blockTime(ji.readLong());
    } else if (fieldEquals("meta", buf, offset, len)) {
      builder.meta(TxMeta.parse(ji));
    } else if (fieldEquals("transaction", buf, offset, len)) {
      if (ji.whatIsNext() == ValueType.ARRAY) {
        ji.openArray();
        builder.data = ji.decodeBase64String();
        ji.skipRestOfArray();
      } else {
        ji.skip();
      }
    } else {
      ji.skip();
    }
    return true;
  };
```

It was curious to me because there doesnt seem to be a call anywhere to `builder.accountKeys()` like with the other fields.

Here is a minimal reproducible example:
```java
    public static void main(String[] args) {
        try (final var httpClient = HttpClient.newBuilder().build()) {
            // Create a RPC client
            final var rpcClient = SolanaRpcClient.createClient(
                    URI.create("https://mainnet.helius-rpc.com/?api-key=YOUR_API_KEY_HERE"),
                    httpClient
                );

            String signature = "3uoR4BXmEo1PiXUrVAEC8kr6Hu619WsTU7obkUGxNAnpAhLgkLNC6WsWuKn7S9PTXWCt6er28ed6q9SpJbPiFLgC";

            Tx transaction = rpcClient.getTransaction(Commitment.CONFIRMED, 0, signature).join();

            System.out.println(transaction.accountKeys()); // returns null
        }
    }

```

**Comment by jpe7s** [comment]
Apologies, this is the remains of support for the [`jsonParsed` functionality from the Solana RPC API](https://solana.com/docs/rpc/http/gettransaction#parameters), which I failed to fully remove, and I no longer intend to support.  

The intended usage is to make use of the [`TransactionSkeleton`](https://github.com/sava-software/sava/blob/49126a113269911dec894728a2d622f911a06326/core/src/main/java/software/sava/core/tx/TransactionSkeleton.java#L23) parser as well as the complete instruction parsers for programs which have Anchor IDL's ([couple of high level examples here](https://github.com/sava-software/anchor-programs/tree/main/examples/src/main/java/software/sava/anchor/program/examples)), or for any SPL programs I've hand written support for in the [solana-programs repo](https://github.com/sava-software/solana-programs/tree/main/src/main/java/software/sava/solana/programs).  

If you have a specific use case I can help provide a usage example, or add the missing functionality if appropriate.

I noticed your example transaction is interacting with the pump .fun program.  Unfortunately it looks like they don't publish their Anchor IDL on chain.  Encouraging them to do so would be helpful and I could generate useful utilities to help interact with their program and parse their transactions.  In the meantime, if they host their IDL on Github or something similar I can use that.

**Comment by jpe7s** [comment]
Fixed in commit 49126a113269911dec894728a2d622f911a06326 which removes unsupported Tx fields.

**Comment by Alec1017** [comment]
ah interesting, thanks for the quick response. 

As for a specific example, I am trying to replicate the javascript code located in this [blog post](https://www.helius.dev/blog/how-to-monitor-solana-transactions-using-geyser-enhanced-websockets#pumpfun-monitor-example).

While pump fun doesnt officially release their IDL, it can still be downloaded from their web client source. I added the IDL in this gist here: https://gist.github.com/Alec1017/960bbdeb50db09f84530b9e864db900c

Any help with the concrete example would be much appreciated 🙏

**Comment by jpe7s** [comment]
[Here is a newer version of the IDL](https://github.com/rckprtr/pumpdotfun-sdk/blob/main/src/IDL/pump-fun.json).  Will put together a usage example tomorrow, but not going to spend too much time on this until it is more official.

**Comment by jpe7s** [comment]
[Here a basic example more in line with your original example transaction](https://github.com/sava-software/sava/blob/main/examples/src/main/java/software/sava/examples/SimpleTxSkeletonExample.java) which is a Buy/Sell swap transaction, unlike the transaction in the blog post which is a token creation transaction.  This example simply parses out the instruction accounts and logs the token mint and buyer.

With respect to the blog post example, some context, the blog is discussing Helius' enhanced geyser web-socket, which requires at least a business account that costs $499/mo at the time of this writing.  Those features are not available via the vanilla Solana RPC web-socket API.

That being said, [here is an example of parsing a create token transaction/instruction](https://github.com/sava-software/anchor-programs/blob/main/examples/src/main/java/software/sava/anchor/program/examples/HelloPumpDotFun.java).  This example logs the new token information and creator.

**Comment by Alec1017** [comment]
great, thank you so much! This is certainly helpful.
